version: "3"
services:
  user_service:
    build: ./user_service
    ports:
      - "8000:8000"

  chat_service:
    build: ./chat_service
    ports:
      - "8001:8001"
    depends_on:
      - user_service
