openapi: 3.0.0
info:
  title: Chat Service API
  version: 1.0.0
paths:
  /message:
    post:
      summary: Send a message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Message"
      responses:
        "200":
          description: Message sent
  /messages:
    get:
      summary: Get all messages for current user
      responses:
        "200":
          description: List of messages
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Message"
components:
  schemas:
    Message:
      type: object
      properties:
        sender:
          type: string
        receiver:
          type: string
        content:
          type: string
      required:
        - sender
        - receiver
        - content
